export default {
    0: {name: 'Gard Caveau'},
    1: {name: 'Mordecai Aven'},
    2: {name: 'Filberte Snowsill'},
    3: {name: 'Field Grice'},
    4: {name: 'Filberte Snowsill'},
    5: {name: 'Edmond mock'},
    6: {name: 'Chaim realy'},
    7: {name: 'John'},
    8: {name: 'Henry yeright'},
    9: {name: 'Hamil Cosham'},
    10: {name: 'Peter piertacovsky'},
    11: {name: 'Adham Cordery'},
    12: {name: 'Audy Wooland'},
    13: {name: 'Rodger Candish'},
    14: {name: 'Ruby Jenkin'},
    15: {name: 'Stavro Boomes'},
    16: {name: 'Maison Batterto'},
    17: {name: 'Orelie Cosgrave'},
    18: {name: 'Yul Kissick'},
    19: {name: 'Stanleigh Pears'},
    20: {name: 'Findlay Sleith'},
    21: {name: 'Wolfgang Ickovits'},
    22: {name: 'Greg Cutbirth'},
    23: {name: 'Gordan Rossant'},
    24: {name: 'Nathan Edmed'},
    25: {name: 'Aldo Lackey'},
    26: {name: 'Sephira Chasmar'},
    27: {name: 'Rhea Garioch'},
    28: {name: 'Hirsch Swanbourne'},
  };